project:
  type: website
  resources:
    - assets/

website:
  title: "Ciències de la Biosfera"
  
  navbar:
    left:
      - text: "Inici"
        href: ca/index.qmd

    right:
      - text: "CA"
        href: /ca/
      - text: "ES"
        href: /es/
      - text: "EN"
        href: /en/

  sidebar:
     style: "docked"
     search: true
     contents:
      - section: "Temes (CA)"
        contents:
          - section: "Tema 1: Sistema Terra"
            href: ca/themes/t01-intro-sistema-terra/index.qmd
            contents:
              - text: "📘 Notes"
                href: ca/themes/t01-intro-sistema-terra/notes.qmd
              - text: "🎞️ Diapositives"
                href: ca/themes/t01-intro-sistema-terra/slides.qmd
              - text: "🧮 Problemes"
                href: ca/themes/t01-intro-sistema-terra/problemes.qmd
              - text: "🧠 Autoavaluació"
                href: ca/themes/t01-intro-sistema-terra/quiz.qmd

      - section: "Activitats"
        contents:
          - activities/practica-r-1.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
    toc: true
    link-citations: true
    css:
      - shared/styles-common.css
      - shared/styles-notes.css

  revealjs:
    theme: simple
    toc: true
    css:
      - shared/styles-common.css
      - shared/styles-slides.css
